---

- hosts: all
  become: true
  tasks:
  - name: install updates on all ubuntu servers
    tags: always
    apt: 
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install appache2 on web servers
    tags: apache2,ubuntu,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: copy html files for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  tasks:

  - name: add ssh key for devops
    tags: always
    authorized_key:
      user: devops
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAmd4FTUm0lYz3tplueSdrcDdeGRgwz94YrTaL3HI+7S ansible"

- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: file_servers
  become: true
  tasks:
  - name: install appache2 ond mariadb-server on file servers
    tags: ubuntu,mariadb,samba
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
        - samba
      state: latest
      update_cache: yes
