---

- hosts: all
  become: true
  tasks:
  - name: install updates on all ubuntu servers
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install appache2 on web servers
    tags: apache2,ubuntu,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: copy html files for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: file_servers
  become: true
  tasks:
  - name: install appache2 ond mariadb-server on file servers
    tags: ubuntu,mariadb,samba
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
        - samba
      state: latest
      update_cache: yes
